
enum SettingsGeneral: String {
    case preference = "x-apple.systempreferences:com.apple.preference"
    case familySettings = "x-apple.systempreferences:com.apple.Family-Settings.extension"
    case softwareUpdate = "x-apple.systempreferences:com.apple.FollowUpSettings.FollowUpSettingsExtension"
    case wifi = "x-apple.systempreferences:com.apple.wifi-settings-extension"
    case bluetooth = "x-apple.systempreferences:com.apple.BluetoothSettings"
    case network = "x-apple.systempreferences:com.apple.Network-Settings.extension"
    case classroomSettings = "x-apple.systempreferences:com.apple.ClassroomSettings"
    case classroomSettings2 = "x-apple.systempreferences:com.apple.Classroom-Settings.extension"
    case notifications = "x-apple.systempreferences:com.apple.Notifications-Settings.extension"
    case sound = "x-apple.systempreferences:com.apple.Sound-Settings.extension"
    case focus = "x-apple.systempreferences:com.apple.Focus-Settings.extension"
    case screenTime = "x-apple.systempreferences:com.apple.Screen-Time-Settings.extension"
    case appearance = "x-apple.systempreferences:com.apple.Appearance-Settings.extension"
    case accessibility = "x-apple.systempreferences:com.apple.Accessibility-Settings.extension"
    case controlCenter = "x-apple.systempreferences:com.apple.ControlCenter-Settings.extension"
    case siri = "x-apple.systempreferences:com.apple.Siri-Settings.extension"
    case spotlight = "x-apple.systempreferences:com.apple.Spotlight-Settings.extension"
    case privacySecurity = "x-apple.systempreferences:com.apple.settings.PrivacySecurity.extension"
    case desktop = "x-apple.systempreferences:com.apple.Desktop-Settings.extension"
    case displays = "x-apple.systempreferences:com.apple.Displays-Settings.extension"
    case wallpaper = "x-apple.systempreferences:com.apple.Wallpaper-Settings.extension"
    case screenSaver = "x-apple.systempreferences:com.apple.ScreenSaver-Settings.extension"
    case battery = "x-apple.systempreferences:com.apple.Battery-Settings.extension"
    case lockScreen = "x-apple.systempreferences:com.apple.Lock-Screen-Settings.extension"
    case touchID = "x-apple.systempreferences:com.apple.Touch-ID-Settings.extension"
    case usersGroups = "x-apple.systempreferences:com.apple.Users-Groups-Settings.extension"
    case passwords = "x-apple.systempreferences:com.apple.Passwords-Settings.extension"
    case passwords2 = "x-apple.systempreferences:com.apple.Passwords"
    case internetAccounts = "x-apple.systempreferences:com.apple.Internet-Accounts-Settings.extension"
    case gameCenter = "x-apple.systempreferences:com.apple.Game-Center-Settings.extension"
    case wallet = "x-apple.systempreferences:com.apple.WalletSettingsExtension"
    case keyboard = "x-apple.systempreferences:com.apple.Keyboard-Settings.extension"
    case mouse = "x-apple.systempreferences:com.apple.Mouse-Settings.extension"
    case trackpad = "x-apple.systempreferences:com.apple.Trackpad-Settings.extension"
    case gameController = "x-apple.systempreferences:com.apple.Game-Controller-Settings.extension"
    case cdDvd = "x-apple.systempreferences:com.apple.CD-DVD-Settings.extension"
    case printScan = "x-apple.systempreferences:com.apple.Print-Scan-Settings.extension"
}

enum SettingsAccessibility: String {
    case main  = "x-apple.systempreferences:com.apple.preference.universalaccess"
    case displ = "x-apple.systempreferences:com.apple.preference.universalaccess?Seeing_Display"
    case zoom  = "x-apple.systempreferences:com.apple.preference.universalaccess?Seeing_Zoom"
    case voiceOver = "x-apple.systempreferences:com.apple.preference.universalaccess?Seeing_VoiceOver"
    case descriptions  = "x-apple.systempreferences:com.apple.preference.universalaccess?Media_Descriptions"
    case captions  = "x-apple.systempreferences:com.apple.preference.universalaccess?Captioning"
    case audio = "x-apple.systempreferences:com.apple.preference.universalaccess?Hearing"
    case keyboard  = "x-apple.systempreferences:com.apple.preference.universalaccess?Keyboard"
    case mouseAndTrackpad  = "x-apple.systempreferences:com.apple.preference.universalaccess?Mouse"
    case switchContro = "x-apple.systempreferences:com.apple.preference.universalaccess?Switch"
    case dictation = "x-apple.systempreferences:com.apple.preference.universalaccess?SpeakableItems"

}

enum SettingsSecurityAndPrivacy: String {
    case main = "x-apple.systempreferences:com.apple.preference.security"
    case general = "x-apple.systempreferences:com.apple.preference.security?General"
    case fileVault = "x-apple.systempreferences:com.apple.preference.security?FDE"
    case firewall = "x-apple.systempreferences:com.apple.preference.security?Firewall"
    case advanced = "x-apple.systempreferences:com.apple.preference.security?Advanced"
    case privacy = "x-apple.systempreferences:com.apple.preference.security?Privacy"
    case privacyCamera = "x-apple.systempreferences:com.apple.preference.security?Privacy_Camera"
    case privacyMicrophone = "x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone"
    case privacyAutomation = "x-apple.systempreferences:com.apple.preference.security?Privacy_Automation"
    case privacyAllFiles = "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles"
    case privacyAccessibility = "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"
    case privacyAssistive = "x-apple.systempreferences:com.apple.preference.security?Privacy_Assistive"
    case privacyLocationServices = "x-apple.systempreferences:com.apple.preference.security?Privacy_LocationServices"
    case privacySystemServices = "x-apple.systempreferences:com.apple.preference.security?Privacy_SystemServices"
    case privacyAdvertising = "x-apple.systempreferences:com.apple.preference.security?Privacy_Advertising"
    case privacyContacts = "x-apple.systempreferences:com.apple.preference.security?Privacy_Contacts"
    case privacyDiagnosticsAndUsage = "x-apple.systempreferences:com.apple.preference.security?Privacy_Diagnostics"
    case privacyCalendars = "x-apple.systempreferences:com.apple.preference.security?Privacy_Calendars"
    case privacyReminders = "x-apple.systempreferences:com.apple.preference.security?Privacy_Reminders"
    case privacyFacebook = "x-apple.systempreferences:com.apple.preference.security?Privacy_Facebook"
    case privacyLinkedIn = "x-apple.systempreferences:com.apple.preference.security?Privacy_LinkedIn"
    case privacyTwitter = "x-apple.systempreferences:com.apple.preference.security?Privacy_Twitter"
    case privacyWeibo = "x-apple.systempreferences:com.apple.preference.security?Privacy_Weibo"
    case privacyTencentWeibo = "x-apple.systempreferences:com.apple.preference.security?Privacy_TencentWeibo"
    /// macOS Catalina 10.15/10.16
    case privacyScreenCapture = "x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture"
    case privacyDevTools = "x-apple.systempreferences:com.apple.preference.security?Privacy_DevTools"
    case privacyInputMonitoring = "x-apple.systempreferences:com.apple.preference.security?Privacy_ListenEvent"
    case privacyDesktopFolder = "x-apple.systempreferences:com.apple.preference.security?Privacy_DesktopFolder"
    case privacyDocumentsFolder = "x-apple.systempreferences:com.apple.preference.security?Privacy_DocumentsFolder"
    case privacyDownloadsFolder = "x-apple.systempreferences:com.apple.preference.security?Privacy_DownloadsFolder"
    case privacyNetworkVolume = "x-apple.systempreferences:com.apple.preference.security?Privacy_NetworkVolume"
    case privacyRemovableVolume = "x-apple.systempreferences:com.apple.preference.security?Privacy_RemovableVolume"
    case privacySpeechRecognition = "x-apple.systempreferences:com.apple.preference.security?Privacy_SpeechRecognition"
    /// macOS Big Sur 10.11/10.16
    case privacyBluetooth = "x-apple.systempreferences:com.apple.preference.security?Privacy_Bluetooth"
    case privacyMusic = "x-apple.systempreferences:com.apple.preference.security?Privacy_Media"
    case privacyHome = "x-apple.systempreferences:com.apple.preference.security?Privacy_HomeKit"
}

enum SettingsDictationAndSpeech: String {
    case dictation = "x-apple.systempreferences:com.apple.preference.speech?Dictation"
    case textToSpeech = "x-apple.systempreferences:com.apple.preference.speech?TTS"
}

enum SettingsSharing: String {
    case main = "x-apple.systempreferences:com.apple.preferences.sharing"
    case screenSharing = "x-apple.systempreferences:com.apple.preferences.sharing?Services_ScreenSharing"
    case fileSharing = "x-apple.systempreferences:com.apple.preferences.sharing?Services_PersonalFileSharing"
    case printerSharing = "x-apple.systempreferences:com.apple.preferences.sharing?Services_PrinterSharing"
    case remoteLogin = "x-apple.systempreferences:com.apple.preferences.sharing?Services_RemoteLogin"
    case remoteManagement = "x-apple.systempreferences:com.apple.preferences.sharing?Services_ARDService"
    case remoteAppleEvents = "x-apple.systempreferences:com.apple.preferences.sharing?Services_RemoteAppleEvent"
    case internetSharing = "x-apple.systempreferences:com.apple.preferences.sharing?Internet"
    case bluetoothSharing = "x-apple.systempreferences:com.apple.preferences.sharing?Services_BluetoothSharing"
}

enum SettingsSoftwareUpdate: String {
    case softwareUpdate = "x-apple.systempreferences:com.apple.preferences.softwareupdate?client=softwareupdateapp"
}
